### ISSUE TITLE
When users are not in /etc/password, multitail dies

### ISSUE THREAD

**Issue by juan-leon** [flok99/multitail#12]
When user has logged in via LDAP or other method (so effective UID is not listed in /etc/passwd), multitail dies with the message:

A problem occured at line 354 in function getuserinfo (from file utils.c):

Failed to get passwd-structure for effective user id XXXX.

**Comment by flok99** [comment]
Does the user have a home dir? And does it have $HOME pointing to it?
thanks

**Comment by juan-leon** [comment]
Yes, the user has a home dir, $HOME points to it, and multitail finds there my .multitailrc.

I neglected to say that I am using version 5.2.8 in Ubuntu 12.04.  multitail seems to work fine, but when I am done for the day and I detach my tmux session, the following day multitail I find multitail dead with the above mentioned message.

I am not sure why multitail needs to find my username, but it seems to be using "getpwuid" and that won't work in systems that use LDAP or simitar (where users are not listed in /etc/passwd)

**Comment by flok99** [comment]
Can you try the new version from github?
I think it may work.
and thanks for reporting the bug!

On Sun, Jan 4, 2015 at 1:42 PM, juan-leon <notifications@github.com> wrote:

> Yes, the user has a home dir, $HOME points to it, and multitail finds
> there my .multitailrc.
>
> I neglected to say that I am using version 5.2.8 in Ubuntu 12.04.
> multitail seems to work fine, but when I am done for the day and I detach
> my tmux session, the following day multitail I find multitail dead with the
> above mentioned message.
>
> I am not sure why multitail needs to find my username, but it seems to be
> using "getpwuid" and that won't work in systems that use LDAP or simitar
> (where users are not listed in /etc/passwd)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/multitail/issues/12#issuecomment-68633293>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by juan-leon** [comment]
I compiled it and now is running.  I suppose tomorrow I will know if it fails.

However, I find the new version missing a feature regarding the one bundled via Ubuntu 12.04 apt-get: the titlebar lacks the "size - date - time" at the right.  Those were useful. I am missing a library or a compilation flag?  I just replaced the binary, no config file was touched.

Thanks

**Comment by flok99** [comment]
Looked at the code and I'm surprised it ever worked!
Fixed it. Can you please verify as well? It worked here but that's not a
guarantee :-)

On Sun, Jan 4, 2015 at 2:10 PM, juan-leon <notifications@github.com> wrote:

> I compiled it and now is running. I suppose tomorrow I will know if it
> fails.
>
> However, I find the new version missing a feature regarding the one
> bundled via Ubuntu 12.04 apt-get: the titlebar lacks the "size - date -
> time" at the right. Those were useful. I am missing a library or a
> compilation flag? I just replaced the binary, no config file was touched.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/multitail/issues/12#issuecomment-68634055>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by juan-leon** [comment]
Works fine here now :-)

**Comment by flok99** [comment]
Good!
Let me know if anything else is broken.

On Sun, Jan 4, 2015 at 2:36 PM, juan-leon <notifications@github.com> wrote:

> Works fine here now :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/multitail/issues/12#issuecomment-68634839>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by juan-leon** [comment]
Thanks!

BTW, an alternative to using "getpwuid", in scenarios where /etc/passwd is not good enough, to get the user name is to use the LOGNAME environment variable.  Posix requires that variable to be set upon login (and also cron sets it).

**Comment by flok99** [comment]
thanks for the suggestion,
i've added it and committed it to github

On Sun, Jan 4, 2015 at 8:22 PM, juan-leon <notifications@github.com> wrote:

> LOGNAME





-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info
