### ISSUE TITLE
multitail.conf should also be searched for in /etc/multitail/

### ISSUE THREAD

**Issue by ck-on** [flok99/multitail#19]
The `make install` routine creates and uses `/etc/multitail/`

But the program only looks in `~/` and  `/etc/multitail.conf`

New installs should go into `/etc/multitail/` to keep things tidy 
and also search for `/etc/multitail/multitail.conf` ?

ps. thanks for sharing this helpful program

**Comment by flok99** [comment]
Good idea! I'll wait for your pull-request. Thanks in advance.

**Comment by flok99** [comment]
no response
