### ISSUE TITLE
watch command

### ISSUE THREAD

**Issue by mgaulton** [flok99/multitail#23]
I'm trying to run 'watch -n 1 "netstat-nat"' in a window of multitail along with some log files but it never gets created as a window. Not sure why, any suggestions?

6.4.1 (this is what comes with opensuse 13.2)

**Comment by flok99** [comment]
Probably too old ticket. But if this still an issue then tell me what commandline you're trying. Closing for now.

**Comment by CWempe** [comment]
I have the same issue.
Or maybe is is more a missing feature.

A simple example would be: `multitail -i /var/log/syslog -l "top"`
This only displays the log file.

But it would be a great feature if multitail could also display output of "graphical" command line tools like `top`.

Other outputs/commands I would like to use in multitail:

* `watch`
* `iotop`
* `iftop`

I think you can summerize these as "tools that reprint the whole screen every X seconds"

**Comment by flok99** [comment]
There's no space between netstat and -nat

On Wed, Nov 11, 2015 at 6:28 PM, mgaulton <notifications@github.com> wrote:

> I'm trying to run 'watch -n 1 "netstat-nat"' in a window of multitail
> along with some log files but it never gets created as a window. Not sure
> why, any suggestions?
>
> 6.4.1 (this is what comes with opensuse 13.2)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/multitail/issues/23>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl www.winnenmetbitcoin.nl

www.aliensdetected.com www.benjeeigenbank.nl www.depersoonlijkebank.nl

www.hackerspace-gouda.nl www.ismijnwebsitekapot.nl www.micro-twin.com

www.slimmetvalutahandelen.nl www.slimwinstmaken.nl www.vertrouwdbankieren.nl

www.watismijnip.info
