### ISSUE TITLE
screen layout on command line rejects legal parameters

### ISSUE THREAD

**Issue by TauPan** [flok99/multitail#25]
multitail -h outputs:
```
 *** screen layout ***
-s x             vertical split screen (in 'x' columns)
-sw x,x,...      at what columns to split the screen, use '0' for automatic size
-sn x,x,...      number of windows per column
-wh x            height of window
```

So I'd like to pass ```-sw 0,30 -sn 0,1``` from a script for a particular set of logs (with a very narrow window on the right).

And the result is
```
 --*- multitail 6.4.3 (C) 2003-2014 by folkert@vanheusden.com -*--

The following problem occured:
-----------------------------
Value for -sw must be > 0.
```

Setting the window configuration to those values via 'j' -> 'm' -> 'e' works.

Similar problem with ```-s 2 -sn 0,1```:
```
 --*- multitail 6.4.3 (C) 2003-2014 by folkert@vanheusden.com -*--

The following problem occured:
-----------------------------
Value for -sn must be > 0.
```

**Comment by flok99** [comment]
Yes that seems to be a bug.
If possible, provide a patch to solve this.
You can send a patch via mail or through github:
https://github.com/flok99/multitail
Thanks in advance.


On Thu, Jan 7, 2016 at 11:28 AM, Friedrich Delgado <notifications@github.com
> wrote:

> multitail -h outputs:
>
>  *** screen layout ***
> -s x             vertical split screen (in 'x' columns)
> -sw x,x,      at what columns to split the screen, use '0' for automatic size
> -sn x,x,      number of windows per column
> -wh x            height of window
>
> So I'd like to pass -sw 0,30 -sn 0,1 from a script for a particular set
> of logs (with a very narrow window on the right)
>
> And the result is
>
>  --*- multitail 643 (C) 2003-2014 by folkert@vanheusdencom -*--
>
> The following problem occured:
> -----------------------------
> Value for -sw must be > 0
>
> Setting the window configuration to those values via 'j' -> 'm' -> 'e'
> works
>
> Similar problem with -s 2 -sn 0,1:
>
>  --*- multitail 643 (C) 2003-2014 by folkert@vanheusdencom -*--
>
> The following problem occured:
> -----------------------------
> Value for -sn must be > 0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/multitail/issues/25>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info
