### ISSUE TITLE
Failure to terminate child process (ssh session)

### ISSUE THREAD

**Issue by nhed** [flok99/multitail#29]
1. Use and server where you have password-less access to and run any long running command.  For example:
   `$ multitail -l "ssh -n rf_ap_svr1 sleep 600"`
2. Hit Control-C to abort
3. Multitail fails to kill the child processes (the remote command as well as the ssh sessions are still alive and now need to be hunted down)
   
   ```
   --*- multitail 6.4.2 (C) 2003-2014 by folkert@vanheusden.com -*--
   
   The following problem occured:
   -----------------------------
   Problem stopping child process with PID 2140 (SIGTERM).
   If this is a bug, please report the following information:
   The last system call returned: 1 which means "Operation not permitted"
   ```

Environment:
- MacBookPro
- OSX El Capitan 10.11.4
- Multitail 6.4.2 installed via homebrew

**Comment by flok99** [comment]
Hi,

I tried it moments ago (on linux) and I cannot reproduce the problem.
Could this be a mac specific problem?

On Sat, Jul 2, 2016 at 1:43 AM, Nevo Hed <notifications@github.com> wrote:

> multitail -l "ssh -n rf_ap_svr1 sleep 600"





-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by nhed** [comment]
I agree it might be, I can try and reproduce on other macs and linux boxes I have access to to check for a pattern

**Comment by flok99** [comment]
Thanks in advance!

On Mon, Jul 4, 2016 at 3:38 PM, Nevo Hed <notifications@github.com> wrote:

> I agree it might be, I can try and reproduce on other macs and linux boxes
> I have access to to check for a pattern
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/flok99/multitail/issues/29#issuecomment-230292856>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADESuHsjOCe2HVPgs6iuXZYq14iT9X9Mks5qSQzZgaJpZM4JDjM9>
> .
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by nhed** [comment]
1. only see this when run from osx
2. Should note that the logged PID is gone by the time (or shortly after) the multitail exits
3. Not sure if related but when I run the same ssh command sans multitail the remote command (sleep 600) remains running even when the connection is dropped (I assume that it will remain running till input/output is performed by the remote command)

(re point 2 - maybe the descriptor closing kills it right after even if the `kill()` failed)

**Comment by nhed** [comment]
Following up on point 3 in my last comment - using `-t` instead of `-n` as parameter to ssh avoids the issue:
 - The remote sleep command is actually gone
 - No local multitail error message

`-t` flag to `ssh` forces a remote tty allocation (running `ssh` in interactive mode, presumably ssh traps and relays the signal).  I could have sworn that I tried that because I am a frequent user of this flag (when running remote instances of `minicom` for example) - but I guess I did not.

[more here](http://unix.stackexchange.com/a/161878/47663)

I would leave it up to you @flok99 if you want to close or not (one could argue that there should not be a local error and there may be an issue in the sequencing of killing the child process)

**Comment by flok99** [comment]
What about adding a note to the man-page?

I'm puzzled by the error.

On Tue, Jul 5, 2016 at 6:14 PM, Nevo Hed <notifications@github.com> wrote:

> Following up on point 3 in my last comment - using -t instead of -n as
> parameter to ssh avoids the issue:
>
>    - The remote sleep command is actually gone
>    - No local multitail error message
>
> -t flag to ssh forces a remote tty allocation (running ssh in interactive
> mode, presumably ssh traps and relays the signal). I could have sworn that
> I tried that because I am a frequent user of this flag (when running remote
> instances of minicom for example) - but I guess I did not.
>
> more here <http://unix.stackexchange.com/a/161878/47663>
>
> I would leave it up to you @flok99 <https://github.com/flok99> if you
> want to close or not (one could argue that there should not be a local
> error and there may be an issue in the sequencing of killing the child
> process)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/flok99/multitail/issues/29#issuecomment-230525823>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADESuMrBChnP0gwUCXoNCUXnFEwikWciks5qSoLIgaJpZM4JDjM9>
> .
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by hasusuf** [comment]
I would like to confirm that this is a macOS specific issue and it's even happening with a simple command like `multitail -r 1 -l "w"` which doesn't require connection establish
