### ISSUE TITLE
Viewing a command's output both in real-time and after it exits

### ISSUE THREAD

**Issue by PeterMinin** [flok99/multitail#30]
I want to run a long-running command, view its output filtered with multitail in real-time, then either let it finish or terminate it manually, and then be able to read the log, ideally in the same window.
Without the manual termination requirement, I've found a couple options:
- `the_command args | multitail -j`
- `multitail -l "the_command args; sleep 100d"`

But with manual termination, there doesn't seem to be an easy way suitable for frequent usage.
- `kill $(pidof the_command)` from a separate terminal
- Adding file output, e.g. `-a run.log`

Is there a way to terminate the command quickly from multitail itself, so that multitail remains open?

**Comment by flok99** [comment]
Check the close_closed_windows configuration parameter
