### ISSUE TITLE
-rc does not clear window

### ISSUE THREAD

**Issue by mvlnmix** [flok99/multitail#36]
`multitail -rc 1 -l free -Rc 1 -l uptime`

The commands do restart but the windows aren't cleared. Tried w/ 6.2.1, 6.4.2 & 5.2.13.

**Comment by flok99** [comment]
please try current version

**Comment by yowzadave** [comment]
I still experience this issue, tested on 6.4.2.

**Comment by broadcastnetworks** [comment]
multitail -rc 3 -l "asterisk -rx 'core show channels verbose' | grep wtf"


The commands do restart but the windows aren't cleared 6.4.2
