### ISSUE TITLE
Use regex like egrep; use REG_ENHANCED

### ISSUE THREAD

**Issue by ClausKlein** [flok99/multitail#38]
It would be nice to have enhanced regular expression features; see re_format(7) for details.

so regex like this can be used:

./pcredemo '(?i)\b(FATAL|ERROR)\b' "pcredemo.c:41:10: fatal error: 'pcre.h' file not found"

Match succeeded at offset 18
 0: fatal
 1: fatal
No named substrings

I would like to use config files like that:
Claus-MacBook-Pro:~ clausklein$ cat ~/.multitailrc
defaultcscheme:regex
colorscheme:regex:kernel and unsorted messages
# segfaults

cs_re_s:red,,bold:kernel: ([^:]_): segfault at [^ ]_ rip [^ ]\* rsp [^ ]\* error
cs_re:yellow:kernel: ._: segfault at [^ ]_ rip [^ ]\* rsp [^ ]\* error
# misc

cs_re:red,,inverse/underline:kernel
cs_re:green:Detected._$
cs_re:green:[
cs_re:green:]
cs_re:cyan::
cs_re:blue|blue,,bold:^... .. ..:..:..
cs_re_s:,,bold:^... .. ..:..:.. [^ ]_ ([A-z0-9]_)
cs_re:red:scanlogd._
# FIXME# cs_re:yellow:\b(NOT|Not|not)\b\w+

cs_re:yellow:[nN][oO][tT]([a-zA-Z0-9.]*)\ 
cs_re:yellow:Can.t
cs_re:yellow:Did.not
# FIXME# cs_re:red:(?i)(failed)

cs_re:red:failed
cs_re:red,yellow,bold:ERROR
cs_re:red,yellow,bold:FATAL
cs_re:yellow:INFO
cs_re:green:WARN
# Date

cs_re_s:yellow: ([0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})
# Thread

cs_re_s:cyan: ([._])
cs_re_s:cyan: [(]([^:)]_)[)]
# Class

cs_re:cyan: (INFO|WARNING|ERROR|DEBUG|FATAL)\ ([a-zA-Z0-9.]*)\ 
# FIXME# cs_re:cyan:(?i)(\b(INFO|WARNING|ERROR|DEBUG|FATAL)s?\b)\ (\w+)\b
# Numbers

cs_re:magenta: ([0-9]{2,})
# Keywords

cs_re_s:green: (UNKNOWN|localhost|handling)\ 
# FIXME# cs_re_s:green:\b(UNKNOWN|localhost|handling)\b

Claus-MacBook-Pro:~ clausklein$

**Comment by flok99** [comment]
regcomp does not support this according to the man-page

**Comment by ClausKlein** [comment]
Yes, according the man page this is not possible, but it was a request to change this, not a bug report!

For most people which know perl regular expressions or use egrep, it would be more easy to write rules.
 
I have tried to change this myself, but the code is not clear to me, so i resigned.
