### ISSUE TITLE
Bug: inverting (-v) an inverted search (-eC) crashes

### ISSUE THREAD

**Issue by foozmeat** [flok99/multitail#42]
I'm on mac os 10.12 running multitail 6.4.2 from homebrew. The following command crashes

`multitail -v -eC '[aA]tom' -i /var/log/system.log`

**Comment by dodona2** [comment]
same on Linux with:
multitail -v -eC '[aA]tom' -i /var/log/syslog
---
mint:17.3
ubuntu:14.04.5 LTS, Trusty Tahr
kernel:Linux 3.19.0-32-generic

**Comment by flok99** [comment]
reproduced

**Comment by flok99** [comment]
fixed
