### ISSUE TITLE
macOS fail make -f makefile.macosx install

### ISSUE THREAD

**Issue by SPDEX** [flok99/multitail#45]
make -f makefile.macosx install
cc -Wall -W utils.o mt.o error.o my_pty.o term.o scrollback.o help.o mem.o cv.o selbox.o stripstring.o color.o misc.o ui.o exec.o diff.o config.o cmdline.o globals.o history.o -lpanel -lncurses -lm  -o multitail
Undefined symbols for architecture x86_64:
  "_send_to_clipboard", referenced from:
      _scrollback_do in scrollback.o
  "_xclip", referenced from:
      _set_xclip in config.o
     (maybe you meant: _set_xclip)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [multitail] Error 1

**Comment by flok99** [comment]
I wonder which version you're using. Not the github version as clipboard.o is missing from the make line.
