### ISSUE TITLE
Update copyright year

### ISSUE THREAD

**Issue by CWempe** [flok99/multitail#59]
Just a little reminder that the copyright information is outdated by four years. :wink: 

https://github.com/flok99/multitail/blob/d0bc45c138931e7099bd2dcab7eff1809a4e161c/clipboard.c#L3

https://github.com/flok99/multitail/blob/d0bc45c138931e7099bd2dcab7eff1809a4e161c/globals.c#L36

**Comment by flok99** [comment]
fixed
