### ISSUE TITLE
Apply a command to logfile

### ISSUE THREAD

**Issue by shang-vikas** [flok99/multitail#61]
Hi,
Thanks for providing this package.It helped me a lot.
I am maintaining multiple log files using daemontools's multilog, a wonderful package to manage services. I am writing a timestamp to every line and that time stamp is encoded by default by multilog. To make it to human-readable form i need to pipe it to another command(tai64nlocal) provided by daemontools. An example would be - 
`cat /path/to/log | tai64nlocal`
How can i do this with multitail ? 
Thanks

**Comment by flok99** [comment]
what about
multitail -l 'cat /path/to/log | tai64nlocal'
