### ISSUE TITLE
Microsecond with -ts

### ISSUE THREAD

**Issue by marco-silva0000** [flok99/multitail#62]
I added %f to the end of the so that line_ts_format on /etc/multitail.conf and it doesn't seem to work, as it adds the literal %f chars after the seconds. 
I dont know if it is a bug or a feature request or if it should work and I have something missconfigured at OS level. this is on a raspberry pi
I also saw [this link](http://php.net/manual/en/function.strftime.php#114532) that can be related

**Comment by flok99** [comment]
Hi,
%f seems a php specific escape, it is not supported by libc
